### ISSUE TITLE
examples_data_path on Jupyter in Docker

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-Exercises#80]
Adding a `print` to the MR notebook `a_fully_sampled`

```
#%% GO TO MR FOLDER
os.chdir(examples_data_path('MR'))
 
print(examples_data_path('MR'))
```
gives 
`/opt/SIRF-SuperBuild/INSTALL/share/SIRF-2.2/data/examples/MR` and you later get the error
 
`'File ptb_resolutionphantom_fully_ismrmrd.h5 not found'`

This file is here on my system
`.../SIRF-SuperBuild/docker/devel/PTB_ACRPhantom_GRAPPA/ptb_resolutionphantom_fully_ismrmrd.h5`

**Comment by KrisThielemans** [comment]
Interesting. This is due to
https://github.com/SyneRBI/SIRF-Exercises/blob/7327df5a0c4456930e1820b49124636c4b6ee8cc/scripts/download_MR_data.sh#L65-L66
The same problem will exist for the PET data
https://github.com/SyneRBI/SIRF-Exercises/blob/7327df5a0c4456930e1820b49124636c4b6ee8cc/scripts/download_PET_data.sh#L68
Also related is #22, which I think is the best solution.

**Comment by ashgillman** [comment]
This should be fixed right?

**Comment by KrisThielemans** [comment]
I guess so. Travis is building some new docker images at the moment. Would be good to give them a spin to check...

**Comment by KrisThielemans** [comment]
it works now
