### ISSUE TITLE
README in each folder

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-Exercises#90]
I think it'd be nice to have a README.md in each folder, especially if jupyter display the README nicely. @ashgillman I saw it doing that for you. A plugin?

**Comment by ashgillman** [comment]
No, I was sharing from GitHub last meeting - which renders the README per directory. I did a quick google, but can't see how to do this.

**Comment by ashgillman** [comment]
Only the MR and Reg notebooks subdirectories don't currently have READMEs.

**Comment by KrisThielemans** [comment]
I had seen this as an abandoned  PR https://github.com/jupyter/notebook/pull/5299. They recommend using https://github.com/NII-cloud-operation/Jupyter-LC_index.

`JupyterLab` does this though.  Maybe time to switch?

**Comment by ashgillman** [comment]
Reading through the thread you posted, it sounds like support for Jupyter Notebooks might be fading. So it could be better to be ahead of the curve with JupyterLab. It also seems to have more features for other data formats.

JupyterLab pros:
- README
- If we could show the terminal/kernel output side-by-side would be very nice for STIR, since a lot of the output is hidden (not sure if this is possible though)
- Continued support and coming features.
cons:
- People, if they're familiar with anything, are more likely to be familiar with Notebooks
- Not sure if its going to be more confusing?
- More changes/testing

**Comment by KrisThielemans** [comment]
Turns out that @casperdcl already install jupyterlab on the docker image (of course). So, as opposed to going to
`http://localhost:9999/`, you just go to `http://localhost:9999/lab`.   On the VM I had to do `python3 -m pip install jupyterlab`; and start with `jupyter lab`.

If you click on a `README.md`, it opens it up in an editor as before, but right-clicking allows you to show it formatted. Not very smooth yet, but at least something.

However
- while the keyboard shortcuts are similar between lab and notebook, for lab it seems very hard to find out what they are (in notebook, you just press `h`)
- `%matplotlib notebook` results in a cryptic error. Seems we'd need to install extra stuff and use `%matplotlib widget`, see
https://stackoverflow.com/questions/51922480/javascript-error-ipython-is-not-defined-in-jupyterlab

A bit too early days for me therefore.

**Comment by ashgillman** [comment]
I was hoping it would automatically preview when navigating to the folder. This still requires users to open the file - a low bar I know but one not all will navigate

**Comment by KrisThielemans** [comment]
yeah, doesn't help a ton.

there was a notebook extension mentioned that does the trick, but I guess it's a bit lower priority at the moment! Let's just get the `README`s in (and some other tiny bits...)

**Comment by KrisThielemans** [comment]
@johannesmayer @ckolbPTB can you please create a `MR/README.md`? Use links for the notebooks.

**Comment by KrisThielemans** [comment]
all done with #129
