### ISSUE TITLE
Cannot reach branch gradient_descent from Jupyter

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF-Exercises#92]
I cloned SIRF-Exercises onto the new VM, checked out branch `gradient_descent` (from PR #85), but I cannot reach it from Jupyter - when I start Jupyter in VM subfolder `notebooks/Synergistic` and get to this subfolder in Jupyter Windows browser, I see VM files on `master`.

**Comment by KrisThielemans** [comment]
did you clone into a different place? Might be easiest to just change the branch in `~/devel/SIRF-Exercises`. This happens because we have a file `~/.jupyter/jupyter_notebook_config.py`. You could also move that out of the way, or create another directory with a config file, and point to that (see `jupyter notebook --help`)

**Comment by evgueni-ovtchinnikov** [comment]
thanks! (I thought `SIRF-Exercises` was part of `SIRF-SuperBuild`...)
